### PR TITLE
added more components

### PR DESCRIPTION
**Pull request by adi-CR7**
this is the progress for item 1 and item 2 for the other component

### CODE REVIEW

**Review by fareez-ahamed — COMMENTED** [review]
I cannot review this since we need at least one commit with the initial project creation.. Akhil has submitted one.. once that's merged only you can raise a request with your changes.. Otherwise I see same files in both of your requests

**Comment by adi-CR7** [comment]
I asked the file from akhil and edited in it.
we are working together

**Comment by fareez-ahamed** [comment]
That isn't how u work with git on a collaborative project

**Comment by adi-CR7** [comment]
next time i will wait till he pushes the code and then i will start coding
.
i did it so that i can work fast.
Really sorry for this time

**Review by fareez-ahamed — COMMENTED** [review]
Rejecting this since its already added from akhils code..

**Comment by adi-CR7** [comment]
Yeah fine understood

**Pull request closed without merging**
